import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "@/Components/Common/ClientProviders";
import Providers from "@/redux/Providers";
import { PrimeReactProvider } from 'primereact/api';
import OffInspect from "@/Components/Common/OffInspect"; 
import NovaChatbot from "@/Components/Common/NovaChatbot";
import CookieConsentBanner from "@/Components/Common/CookieConsentBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Website Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning translate="no">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <OffInspect />
        <ClientProviders />
        <Providers>
          <PrimeReactProvider>
            {children}
            <CookieConsentBanner />
           {/* 
           <NovaChatbot /> 
           */} 
          </PrimeReactProvider>
        </Providers>
      </body>
    </html>
  );
}