export interface IPropulserieResourceTheme {
  theme: string;
  keywords: string[];
  books: string[];
  podcasts: string[];
  exercises: string[];
  capsules: string[];
  mentors: string[];
}

/** Official Propulserie resource library — 18 themes per Marie's PDF. AI must only recommend from this list. */
export const PROPULSERIE_RESOURCE_LIBRARY: IPropulserieResourceTheme[] = [
  {
    theme: 'Confiance en soi',
    keywords: ['confiance', 'peur', 'oser', 'légitimité', 'doute', 'confidence', 'imposteur'],
    books: ['Imparfaits, libres et heureux (Christophe André)', 'Oser : Thérapie de la confiance en soi (Frédéric Fanget)'],
    podcasts: ['Métamorphose', 'Change ma vie'],
    exercises: ['Journal des réussites', 'Liste des forces', 'Défi « une action inconfortable par semaine »'],
    capsules: ['Oser prendre sa place'],
    mentors: ['Coach', 'Dirigeant', 'Entrepreneur'],
  },
  {
    theme: 'Estime de soi',
    keywords: ['estime', 'valeur', 'respect', 'soi', 'self-worth'],
    books: ["L'estime de soi (André & Lelord)", 'La confiance en soi (Isabelle Filliozat)'],
    podcasts: ['Change ma vie', 'La Leçon'],
    exercises: ['Lettre à soi-même', 'Recensement des qualités reconnues par l\'entourage', 'Gratitude personnelle'],
    capsules: ['Renforcer son estime'],
    mentors: ['Coach', 'Mentor développement personnel'],
  },
  {
    theme: 'Communication',
    keywords: ['communication', 'relation', 'parole', 'écoute', 'feedback', 'conversation'],
    books: ['Les mots sont des fenêtres (Rosenberg)', "Cessez d'être gentil, soyez vrai (Thomas d'Ansembourg)"],
    podcasts: ['Métamorphose', 'Vlan !'],
    exercises: ['Préparer une conversation difficile', 'Reformulation active', 'Écoute active pendant une semaine'],
    capsules: ['Mieux communiquer'],
    mentors: ['Manager', 'RH', 'Formateur'],
  },
  {
    theme: 'Burn-out / Épuisement professionnel',
    keywords: ['burn-out', 'burnout', 'épuisement', 'surmenage', 'fatigue chronique'],
    books: ['Le burn-out (Christophe André)', 'Je ne suis pas sortie de mon burn-out pour rien (Alexandra Reynaud)'],
    podcasts: ['Métamorphose', 'InPower'],
    exercises: ['Cartographie énergie/fatigue', 'Audit des sources de stress', 'Plan de récupération'],
    capsules: ['Comprendre ses limites'],
    mentors: ['RH', 'Coach', 'Ancien burn-out'],
  },
  {
    theme: 'Gestion du stress',
    keywords: ['stress', 'anxiété', 'équilibre', 'tension', 'surcharge', 'calme'],
    books: ['Méditer jour après jour (Christophe André)', 'Trois amis en quête de sagesse'],
    podcasts: ['Métamorphose', 'Émotions'],
    exercises: ['Cohérence cardiaque 365', 'Respiration carrée', 'Scan corporel'],
    capsules: ['Retrouver son équilibre'],
    mentors: ['Sophrologue', 'Coach', 'Dirigeant'],
  },
  {
    theme: 'Reconversion professionnelle',
    keywords: ['reconversion', 'changement', 'transition', 'carrière', 'career', 'pivot'],
    books: ['Trouver sa voie (Catherine Testa)', 'Oser changer (Saverio Tomasella)'],
    podcasts: ['Le Gratin', 'Génération Do It Yourself', 'Métamorphose'],
    exercises: ['Ligne de vie', 'Cartographie des compétences', 'Analyse des moments de fierté'],
    capsules: ['Explorer de nouvelles voies'],
    mentors: ['Entrepreneur', 'Mentor reconversion'],
  },
  {
    theme: 'Sens au travail',
    keywords: ['sens', 'meaning', 'purpose', 'valeurs', 'alignement', 'motivation profonde'],
    books: ["La vie a plus d'imagination que nous (Clarisse Gardet)", "L'entreprise nouvelle génération (Isaac Getz)"],
    podcasts: ['Vlan !', 'Génération Do It Yourself'],
    exercises: ['Exercice des valeurs', 'Journée idéale dans 5 ans', 'Activités énergisantes'],
    capsules: ['Retrouver du sens'],
    mentors: ['Entrepreneur', 'Dirigeant'],
  },
  {
    theme: "Syndrome de l'imposteur",
    keywords: ['imposteur', 'imposter', 'illégitime', 'fraude', 'doute de soi'],
    books: ['Les Vertus de l\'échec (Charles Pépin)', 'Oser réussir (Carol Dweck)'],
    podcasts: ['La Leçon', 'Métamorphose'],
    exercises: ['Liste des réussites', 'Collecte de feedbacks positifs', 'Journal des victoires'],
    capsules: ['Oser sa légitimité'],
    mentors: ['Entrepreneur', 'Dirigeant'],
  },
  {
    theme: 'Leadership',
    keywords: ['leadership', 'manager', 'diriger', 'équipe', 'vision'],
    books: ['Les Vertus de l\'échec (Charles Pépin)', 'Le leadership bienveillant'],
    podcasts: ['Génération Do It Yourself', 'Le Gratin'],
    exercises: ['Feedback 360°', 'Analyse de son style de leadership', 'Définition de sa vision'],
    capsules: ['Développer son leadership'],
    mentors: ['DG', 'Dirigeant', 'Manager'],
  },
  {
    theme: 'Prise de parole',
    keywords: ['parole', 'public', 'présentation', 'pitch', 'expression orale'],
    books: ['Parler en public TED (Carmine Gallo)', 'Convaincre en moins de 2 minutes'],
    podcasts: ['TEDx France', 'Le Gratin'],
    exercises: ['Enregistrement vidéo', 'Pitch de 2 minutes', 'Storytelling personnel'],
    capsules: ["Oser s'exprimer"],
    mentors: ['Conférencier', 'Formateur'],
  },
  {
    theme: 'Équilibre vie professionnelle / vie personnelle',
    keywords: ['équilibre', 'work-life', 'balance', 'famille', 'temps personnel'],
    books: ["L'art de l'essentiel (Greg McKeown)", 'Le pouvoir du moment présent'],
    podcasts: ['Métamorphose', 'Change ma vie'],
    exercises: ['Audit du temps', 'Semaine idéale', 'Suppression d\'une activité énergivore'],
    capsules: ['Rééquilibrer son quotidien'],
    mentors: ['Parent entrepreneur', 'Dirigeant'],
  },
  {
    theme: 'Motivation',
    keywords: ['motivation', 'élan', 'énergie', 'procrastination', 'action', 'moteur'],
    books: ['Drive (Daniel Pink)', "L'homme qui voulait être heureux (Laurent Gounelle)"],
    podcasts: ['Métamorphose', 'Simon Sinek'],
    exercises: ['Identifier ses moteurs', 'Retrouver ses sources d\'énergie', 'Expérimentation d\'une nouvelle activité'],
    capsules: ['Retrouver son élan'],
    mentors: ['Coach', 'Entrepreneur'],
  },
  {
    theme: 'Relations professionnelles',
    keywords: ['relation', 'collègue', 'équipe', 'conflit', 'collaboration'],
    books: ['Entouré d\'idiots (Thomas Erikson)', 'Les mots sont des fenêtres'],
    podcasts: ['Vlan !', 'Génération Do It Yourself'],
    exercises: ['Cartographie relationnelle', 'Analyse des relations ressources / toxiques'],
    capsules: ['Améliorer ses relations'],
    mentors: ['RH', 'Manager'],
  },
  {
    theme: 'Prise de décision',
    keywords: ['décision', 'choix', 'hésitation', 'arbitrage', 'dilemme'],
    books: ['Savoir décider (Jacques Salomé)', 'Les Vertus de l\'échec (Charles Pépin)'],
    podcasts: ['Vlan !', 'Métamorphose'],
    exercises: ['Arbre de décision', 'Pré-mortem', 'Liste bénéfices/risques'],
    capsules: ['Décider avec confiance'],
    mentors: ['Dirigeant', 'Entrepreneur'],
  },
  {
    theme: 'Gestion du temps',
    keywords: ['temps', 'organisation', 'priorité', 'productivité', 'planning'],
    books: ['Avalez le crapaud (Brian Tracy)', 'Une journée de 24 heures'],
    podcasts: ['Deep Life', 'Le Gratin'],
    exercises: ['Matrice Eisenhower', 'Blocage du temps', 'Audit des distractions'],
    capsules: ['Reprendre le contrôle de son temps'],
    mentors: ['Manager', 'Entrepreneur'],
  },
  {
    theme: "Recherche d'emploi / Évolution de carrière",
    keywords: ['emploi', 'recrutement', 'cv', 'entretien', 'carrière', 'évolution'],
    books: ['Réussir son repositionnement professionnel (Apec)', 'Trouver sa voie'],
    podcasts: ['Génération Do It Yourself'],
    exercises: ['Relecture du parcours', 'Identification des compétences clés', 'Pitch professionnel'],
    capsules: ['Construire son projet professionnel'],
    mentors: ['RH', 'Recruteur', 'Dirigeant'],
  },
  {
    theme: 'Entrepreneuriat',
    keywords: ['entrepreneur', 'startup', 'business', 'création', 'entreprise'],
    books: ['La semaine de 4 heures', 'Tout le monde n\'a pas eu la chance de rater ses études (Olivier Roland)'],
    podcasts: ['Le Gratin', 'Génération Do It Yourself'],
    exercises: ['Business Model Canvas simplifié', 'Test d\'idée', 'Identification des risques'],
    capsules: ['Oser entreprendre'],
    mentors: ['Entrepreneur', 'Fondateur'],
  },
  {
    theme: 'Gestion des émotions',
    keywords: ['émotion', 'colère', 'tristesse', 'joie', 'intelligence émotionnelle'],
    books: ["L'intelligence émotionnelle (Daniel Goleman)", 'Au cœur des émotions de l\'enfant (Filliozat)'],
    podcasts: ['Métamorphose', 'Émotions'],
    exercises: ['Journal émotionnel', 'Roue des émotions', 'Identification des déclencheurs'],
    capsules: ['Mieux comprendre ses émotions'],
    mentors: ['Coach', 'Sophrologue'],
  },
];
